### ISSUE TITLE
Make HomeAbsolute command fast

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/Team100Swerve#3]
The current implementation of HomeAbsolute will slowly turn the wheels until they reach their home orientation. This is fine for testing and development but could eat into autonomous time during a match. How can we make this faster? Hint: we already have a way to turn the wheels quickly to a desired angle.

**Comment by brettle** [comment]
I don't think the following lines make sense:

https://github.com/DeepBlueRobotics/Team100Swerve/blob/8a8c66d919f59b87affe7e80790442c638d03066/src/main/java/frc/robot/commands/HomeAbsolute.java#L66-L86

the `*_ZERO` values were taken from the absolute/analog encoders, but the calls to `getSelectedSensorPosition()` will return values from the incremental/quadrature encoders (because that's the encoder you selected in `initialize()`. The different types of encoders have different units and offsets.

**Comment by alexander-mcdowell** [comment]
My mistake. I was intending to use Robot.drivetrain.*Turn.getSensorCollection().getAnalogIn() but I forgot to change those lines.

**Comment by brettle** [comment]
Better, but the values returned by getAnalogIn() have different units than those returned by the quad encoders, so you can't pass the raw difference to setAngle().

**Comment by alexander-mcdowell** [comment]
I am using that difference to control the sign of the angle value that is passed into setAngle. If the speed is too fast and it doesn't converge, or is too slow, then all that needs to be done is change the angle. I do not believe I am passing the raw difference.

**Comment by brettle** [comment]
`setAngle()` tells the motor controller to use position PID to go to the specified angle as measured by the currently configured sensor (which is not the analog sensor as the code stands).  It doesn't use the specified angle to control how fast it moves in a particular direction.

**Comment by alexander-mcdowell** [comment]
Ah, I see. Before setAngle is called, convertAngle is called, given a speed and quad encoder position. I need to call that using the speed and the quad encoder position before calling setAngle.

**Comment by alexander-mcdowell** [comment]
I pushed some code that simplifies the HomeAbsolute command by using .move from SwerveEnclosure with 0.0 speed.

**Comment by brettle** [comment]
Fixed.
